//Game constants
const FRAME_RATE = 60;
const CHARACTER_HORIZONTAL_SPEED = 10;
const CHARACTER_JUMP_OFFSET = -20;
const GRAVITY = 0.7;
const PLAYER_COLOR = "red";
const ENEMY_COLOR = "green";
const GAME_SCREEN_HEIGHT = 576;
const GAME_SCREEN_WIDTH = 1024;

module.exports = {
  FRAME_RATE,
  CHARACTER_HORIZONTAL_SPEED,
  GRAVITY,
  CHARACTER_JUMP_OFFSET,
  ENEMY_COLOR,
  PLAYER_COLOR,
  GAME_SCREEN_HEIGHT,
  GAME_SCREEN_WIDTH,
};
