//Game constants
const FRAME_RATE = 10;
const CHARACTER_HORIZONTAL_SPEED = 5;
const CHARACTER_JUMP_OFFSET = -20;
const GRAVITY = 0.3;
const PLAYER_COLOR = 'red';
const ENEMY_COLOR = 'green';
const GAME_SCREEN_HEIGHT = 1024;
const GAME_SCREEN_WIDTH = 570;

module.exports = {
    FRAME_RATE,
    CHARACTER_HORIZONTAL_SPEED,
    GRAVITY,
    CHARACTER_JUMP_OFFSET,
    ENEMY_COLOR,
    PLAYER_COLOR,
    GAME_SCREEN_HEIGHT,
    GAME_SCREEN_WIDTH
}