/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Ninja(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("../../assets/Ninja.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch24" geometry={nodes.Ch24.geometry} material={materials.Ch24_Body} skeleton={nodes.Ch24.skeleton} />
        </group>
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <primitive object={nodes.mixamorigHips_1} />
          <skinnedMesh name="Ch24001" geometry={nodes.Ch24001.geometry} material={materials["Ch24_Body.001"]} skeleton={nodes.Ch24001.skeleton} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Ninja.glb");
