/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function NinjaAnim(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/NinjaAnim.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.idle.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, -0.3]} scale={0.025}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Ch24" geometry={nodes.Ch24.geometry} material={materials["Ch24_Body.001"]} skeleton={nodes.Ch24.skeleton} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/NinjaAnim.glb");
