version: "3"
services:
  mongo:
    image: "mongo"
  nginx:
    image: nginx:1.22.0-alpine
    container_name: nginx
    restart: always
    depends_on:
      - api
      - client
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      # Host:Container
      - "80:80"
      - "443:443"
  api:
    build:
      dockerfile: Dockerfile
      context: "./Back-End"
    volumes:
      - /app/node_modules
      - ./Back-End:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./Front-End
    volumes:
      - /app/node_modules
      - ./Front-End:/app
