version: "3"
services:
  mongo:
    image: "mongo"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile
      context: "./Back-End"
    volumes:
      - /app/node_modules
      - ./Back-End:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./Front-End
    volumes:
      - /app/node_modules
      - ./Front-End:/app

