version: '3'
services:
  api:
    container_name: api-container
    image: ghcr.io/khanm253/express-env-1:latest
    expose:
      - "3001"
    ports: 
      - "3001:3001"
    depends_on:
      - mongo
  client:
    container_name: client-container
    image: ghcr.io/khanm253/client-env-3:latest 
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - api
  mongo:
    container_name: mongo-backend
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - apidb:/data/apidb
volumes:
  apidb:
