apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  labels:
    app: express-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: sahilhakimi/express-api:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: "mongodb://treyarchSahil:treyarchPass@mongodb-service.default.svc.cluster.local:27017"
          # - name: MONGO_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongodb-secret
          #       key: mongo-root-username
          # - name: MONGO_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongodb-secret
          #       key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
